version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PG_Admin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgadmin_data:

networks:
  mynetwork:
    driver: bridge
