version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge